### ISSUE TITLE
problem with jade fitlers (jstransformer-scss)

### ISSUE THREAD

**Issue by geyang** [gulp-community/gulp-pug#106]
Hi, thanks in advance!

I am using the `jstransformer-scss` in my jade. Here is how I am using the filter in my express server. Somehow the same syntax does not work with gulp-jade
### Server setup that works:

``` javascript
/* express setup: */
var jade = require('jade') // version 1.11.0
var scssTransformer = require('jstransformer-scss') // version 0.12.0
var jstransformer = require('jstransformer');

jade.filters.scss = jstransformer(scssTransformer);

app.set('view engine', 'jade')

```
### gulp-jade setup that does not work:

The same setup with gulp-jade does not work:

``` javascript
var jade = require('jade') // version 1.11.0
var scssTransformer = require('jstransformer-scss') // version 0.12.0
var jstransformer = require('jstransformer');

jade.filters.scss = jstransformer(scssTransformer);

gulp.task('jade', function () {
    var jadePipette = gulpJade({
        jade: jade,
        pretty: false
    });
    jadePipette.on('error', errorHandler);
    return gulp.src(jadeSource)
        .pipe(jadePipette)
        .pipe(gulp.dest('./dist/'))
});

```

What could be wrong?
### stack trace:

``` bash
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: /Users/user/projects/project-new/project-app/src/index.jade:5
    3| block body-container
    4|     style
  > 5|         include:scss ../../components/style-hero/hero.scss
    6|     .hero
    7|         .pauser-width-container.flex-row-container.flex-justify
    8|             - var imauserScale = '555px';

unknown filter ":scss"
    at filter (/Users/user/projects/project-new/node_modules/jade/lib/filters.js:93:13)
    at Parser.parseInclude (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:596:13)
    at Parser.parseExpr (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:223:21)
    at Parser.block (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:729:25)
    at Parser.tag (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:838:24)
    at Parser.parseTag (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:759:17)
    at Parser.parseExpr (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:211:21)
    at Parser.block (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:729:25)
    at Parser.parseBlock (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:535:14)
    at Parser.parseExpr (/Users/user/projects/project-new/node_modules/jade/lib/parser.js:215:21)

```

**Comment by geyang** [comment]
This is resolved after I read the source code of jade:

https://github.com/jadejs/jade/issues/2145
