### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by red2678** [gulp-community/gulp-pug#107]
I just upgraded all my packages. Now runing gulp-jade ver 1.1.0 and unforuntally I am now getting this error when I run my gulp task.

**TypeError: dest.on is not a function**

Could this be related to gulp-jade?

Here is my task, it is a basic task with no options:

```
gulp.task('jade', function() {
    return gulp.src(config.sources.jade, {
        base : config.getSrcDir()
    })
        .pipe(jade())
        .pipe(gulp.dest('./html'));
});
```

Console Output:

```
[18:51:25] Starting 'jade'...
[18:51:25] 'jade' errored after 2.34 ms
[18:51:25] TypeError: dest.on is not a function
    at DestroyableTransform.Stream.pipe (stream.js:45:8)
    at Gulp.<anonymous> (/xxx/xxx/gulpfile.js:423:4)
    at module.exports (/xxx/xxx/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/xxx/xxx/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/xxx/xxx/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /xxx/xxx/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (xxx/xxx/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/xxx/xxx/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/xxx/xxx/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/xxx/xxx/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
```

**Comment by red2678** [comment]
Please disregard

**Comment by DinisCruz** [comment]
I just got the same error, how did you solved it?

**Comment by DinisCruz** [comment]
ok found it, it was caused by not calling the pug function

here is the code that threw this error

``` coffee
gulp.task 'compile-pug', ()->
  gulp.src pug_Folder
      .pipe pug
      .pipe gulp.dest './dist/html'
```

here is the code with the solution

``` coffee
pug         = require 'gulp-pug'

source_Folder = './src/**/*.coffee'
pug_Folder    = './views/*.pug'

gulp.task 'compile-pug', ()->
  gulp.src pug_Folder
      .pipe pug()
      .pipe gulp.dest './dist/html'
```
