### ISSUE TITLE
TypeError: Cannot create property 'cwd' on string '!src/**/_*.pug'

### ISSUE THREAD

**Issue by theskillwithin** [gulp-community/gulp-pug#118]
```
[18:56:48] Starting 'pug'...
[18:56:48] 'pug' errored after 1.85 ms
[18:56:48] TypeError: Cannot create property 'cwd' on string '!src/**/_*.pug'
    at Object.gs.createStream (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.js:19:46)
    at Object.gs.create (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/index.js:68:42)
    at Gulp.src (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/Users/Austin/Projects/heartcup/gulpfile.js:32:14)
    at module.exports (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Users/Austin/Projects/heartcup/node_modules/gulp/index.js:36:18)
    at Gaze.<anonymous> (/Users/Austin/Projects/heartcup/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:18:14)

```

gulp config:

```
gulp.task('pug', function() {
        gulp.src('src/**/*.pug','!src/**/_*.pug')
        .pipe(pug()) // pip to jade plugin
        .pipe(gulp.dest('src')); // tell gulp our output folder
});


gulp.watch('src/*.pug',['pug']);
```

**Comment by theskillwithin** [comment]
my bad:

fix:
gulp.src(['src/**/*.pug','!src/**/_*.pug'])
