### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by DinisCruz** [gulp-community/gulp-pug#130]
I just started having this error (see full stacktrace below)

looks like it is happening in the pug-linker module. Any ideas of what is the problem?

for reference here is how I'm using it 

``` coffee
gulp.task 'compile-pug', ()->
  gulp.src pug_Files
      #.pipe plumber()
      .pipe pug()
      .pipe gulp.dest html_Folder
```

```
MacBook-Pro-2:ui diniscruz$ gulp compile-pug
[11:36:06] Requiring external module coffee-script/register
[11:36:07] Using gulpfile ~/GitHub_REPOS/Maturity-Models/ui/gulpfile.coffee
[11:36:07] Starting 'compile-pug'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'type' of undefined
  at link (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-linker/index.js:12:13)
  at after (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-linker/index.js:110:26)
  at walkAST (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:78:12)
  at /Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:21:16
  at Array.map (native)
  at walkAST (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:20:29)
  at walkAST (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:33:21)
  at /Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:21:16
  at Array.map (native)
  at walkAST (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:20:29)
  at walkAST (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:33:21)
  at /Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:21:16
  at Array.map (native)
  at walkAST (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-walk/index.js:20:29)
  at applyIncludes (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-linker/index.js:104:10)
  at link (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug-linker/index.js:21:9)
  at compileBody (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug/lib/index.js:134:9)
  at Object.exports.compile (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/pug/lib/index.js:206:16)
  at DestroyableTransform.compilePug (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/gulp-pug/index.js:33:26)
  at DestroyableTransform.Transform._read (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
  at DestroyableTransform.Transform._write (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
  at doWrite (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
  at writeOrBuffer (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
  at DestroyableTransform.Writable.write (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
  at write (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:166:7)
  at emitReadable_ (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:166:7)
  at emitReadable_ (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /Users/diniscruz/GitHub_REPOS/Maturity-Models/ui/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:404:3)
```

**Comment by jamen** [comment]
The only reference back to `gulp-pug` in the stack trace is from line 33, which is simply where it compiles using pug.  So it seems that it might be an error with pug itself.  

Because there is a lot of references to the AST in the trace it could be a syntax error handled badly, so you might want to check the source too.

Note that if this is a problem with pug, they could have fixed this in a later version, try doing `npm install pug@latest` and pass in your own instance of the new beta.  I'm not updating until they get v2 out, because the only non-prereleased versions are deprecated.

**Comment by DinisCruz** [comment]
ok the prob was caused by something on the fluentnode project, so I'm closing this
