### ISSUE TITLE
Error with unknown :custom filter

### ISSUE THREAD

**Issue by sntiagomoreno** [gulp-community/gulp-pug#134]
Pug gets compiled fine, but an error is being thrown each time it runs the task:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: /Users/Santiago/Documents/Correos/node_modules/pug-filters/test/cases/filters.include.custom.pug:4

unknown filter ":custom"
    at makeError (/Users/Santiago/Documents/Correos/node_modules/pug-error/index.js:32:13)
    at filterWithFallback (/Users/Santiago/Documents/Correos/node_modules/pug-filters/lib/handle-filters.js:52:17)
    at filterFileWithFallback (/Users/Santiago/Documents/Correos/node_modules/pug-filters/lib/handle-filters.js:62:16)
    at walk.includeDependencies (/Users/Santiago/Documents/Correos/node_modules/pug-filters/lib/handle-filters.js:33:18)
    at walkAST (/Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:13:26)
    at /Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:21:16
    at Array.map (native)
    at walkAST (/Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:20:29)
    at walkAST (/Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:33:21)
    at /Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:21:16
    at Array.map (native)
    at walkAST (/Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:20:29)
    at walkAST (/Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:33:21)
    at /Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:21:16
    at Array.map (native)
    at walkAST (/Users/Santiago/Documents/Correos/node_modules/pug-walk/index.js:20:29)
```

**Comment by jamen** [comment]
The error doesn't tell me much unfortunately.  Looks like it is coming from a test case in `pug-filters`, which is odd.

Perhaps try using the latest prereleased version (`npm install --save pug@latest`) with [`opts.pug`](https://github.com/jamen/gulp-pug#pugopts).

If that doesn't work, I'd probably need to see some source code.

**Comment by jamen** [comment]
A patch was published that includes the most recent prerelease of `v2`.  Can you try installing the latest version `gulp-pug@3.0.4` and let me know if that solves it?

Otherwise, this error looks quite strange.  It's coming from a test case in `pug-filters`.

**Comment by sntiagomoreno** [comment]
Hi, didn't work. I've updated to Gulp 4, still throws an error but don't know if this is more descriptive than above?:

```
[09:56:35] Using gulpfile ~/Code/correos-cnmh/gulpfile.js
[09:56:35] Starting 'views'...
[09:56:50] 'views' errored after 14 s
[09:56:50] Error in plugin 'gulp-pug'
Message:
    /Users/Sntiago/Code/correos-cnmh/node_modules/pug-filters/test/cases/filters.include.custom.pug:4

unknown filter ":custom"
Details:
    code: PUG:UNKNOWN_FILTER
    msg: unknown filter ":custom"
    line: 4
    column: undefined
    filename: /Users/Sntiago/Code/correos-cnmh/node_modules/pug-filters/test/cases/filters.include.custom.pug
    src: undefined
    toJSON: function () {
    return {
      code: this.code,
      msg: this.msg,
      line: this.line,
      column: this.column,
      filename: this.filename
    };
  }
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

Thank you!

**Comment by hlissner** [comment]
In case you're still getting this error: it's likely caused by an over-zealous gulp.src glob capturing the test case templates in `node_modules/pug-filters/test/cases/*.pug`.

i.e. `gulp.src("**/*.pug")` captures `node_modules/pug-filters/test/cases/filters.include.custom.pug`

So you'll want to exclude node_modules.

**Comment by jamen** [comment]
Good idea @hlissner, didn't quite occur to me.

**Comment by sntiagomoreno** [comment]
Working perfectly now. Thanks @hlissner and thanks @jamen for the plugin.
