### ISSUE TITLE
Cant run task

### ISSUE THREAD

**Issue by felipe3dfx** [gulp-community/gulp-pug#139]
Have the follow:

```
gulp.task('compile-pug', function() {
    gulp.src('static/**/*.pug')
        .pipe(pug({
            pretty: true
        }))
    .pipe(pug().on('error', pug.logError))
    .pipe(gulp.dest('public'));
});
```

When run gulp compile-pug raises error:

```
[22:49:11] Using gulpfile /code/gulpfile.js
[22:49:11] Starting 'compile-pug'...
[22:49:11] 'compile-pug' errored after 13 ms
[22:49:11] TypeError: "listener" argument must be a function
    at _addListener (events.js:216:11)
    at DestroyableTransform.addListener (events.js:275:10)
    at DestroyableTransform.Readable.on (/code/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:650:33)
    at Gulp.<anonymous> (/code/gulpfile.js:21:17)
    at module.exports (/code/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/code/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/code/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/code/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

my package.json:

```
  "dependencies": {
    "browser-sync": "^2.14.0",
    "graceful-fs": "^4.1.5",
    "gulp": "^3.9.1",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^1.6.0",
    "pug": ">=2.0.0-alpha <3",
    "gulp-pug": "^3.0.4"
  }
}
```

Any ideas?

**Comment by Yhubee** [comment]
Have you tried taking out this line:
`.pipe(pug().on('error', pug.logError))`
?

**Comment by jamen** [comment]
Hello, sorry for late reply.

`pug.logError` is not a function and never has been a function in `gulp-jade` either, I believe.  Which is why your event listener is not a function, rather undefined.  I would suggest using `gulp-plumber` maybe.

If this sort of `.logError` thing is a common practice (which I would be unaware of), I'm open to PRs.  :smile:
