### ISSUE TITLE
Unexpected token, acorn.js

### ISSUE THREAD

**Issue by danieldafoe** [gulp-community/gulp-pug#147]
Hi there,

Currently trying to port over the organization's Jade to Pug, but getting this error. I'm using the gulp-pug package.

_Versions_
Node.js: 6.2.0
npm: 3.8.9
gulp-pug: ^3.1.0

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token (205:0)
    at Parser.pp$4.raise (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$2.parseBindingAtom (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:1417:12)
    at Parser.pp$1.parseVarId (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:1049:20)
    at Parser.pp$1.parseVar (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:1032:14)
    at Parser.pp$1.parseVarStatement (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:917:10)
    at Parser.pp$1.parseStatement (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:706:19)
    at Parser.pp$1.parseTopLevel (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn/dist/acorn.js:3098:39)
    at reallyParse (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn-globals/index.js:22:16)
    at findGlobals (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/acorn-globals/index.js:35:11)
    at addWith (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/node_modules/with/index.js:29:14)
    at Object.Compiler.compile (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/index.js:129:12)
    at generateCode (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug-code-gen/index.js:32:39)
    at compileBody (/Users/danieldafoe/Desktop/olb-day1/node_modules/pug/lib/index.js:170:12)
```

Any help would be greatly appreciated!

**Comment by jamen** [comment]
Hey.  Please look at [Migrating to Pug 2](https://pugjs.org/api/migration-v2.html).  There is some syntax changes which I'm guessing might be related.

Otherwise, reopen issue with more information.  Thanks
