### ISSUE TITLE
Compiling from PUG to HTML is not working

### ISSUE THREAD

**Issue by ivanprotsko** [gulp-community/gulp-pug#152]
Please, help me.

In the older version this code is working:

```
gulp.task('views', function buildHTML() {
return gulp.src('build//*.pug')
.pipe(watch('build//*.pug'))
.pipe(pug({ yourTemplate: 'Locals' }))
.pipe(gulp.dest('public/'))
.pipe(livereload({ start: true }));
});

```
yesterday I am upgrade to latest version and now getting this error:

```
TypeError: pug is not a function
at Gulp.buildHTML (/Users/prots/Projects/learn-javascript/gulpfile.js:43:13)
at module.exports (/Users/prots/node_modules/orchestrator/lib/runTask.js:34:7)
at Gulp.Orchestrator._runTask (/Users/prots/node_modules/orchestrator/index.js:273:3)
at Gulp.Orchestrator._runStep (/Users/prots/node_modules/orchestrator/index.js:214:10)
at Gulp.Orchestrator.start (/Users/prots/node_modules/orchestrator/index.js:134:8)
at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
at Function.Module.runMain (module.js:577:11)
at startup (node.js:160:18)
```

Tell me, please, how I can fix this problem?

**Comment by ivanprotsko** [comment]
Resolved.

I am deleted this row **var pug = require("pug");**

**Comment by jamen** [comment]
:+1:
