### ISSUE TITLE
SyntaxError is thrown too late and hard/not to understand

### ISSUE THREAD

**Issue by timaschew** [gulp-community/gulp-pug#88]
I have some gulp tasks, first I compiling the jade templates, then some static copy tasks are executed.

My output is this:

```
[09:30:58] Finished 'collection-templates' after 1.07 s
[09:30:58] Starting 'styles'...
[09:30:59] Starting 'static'...
```

But immediately after this line I get this error below. If I disable the **colleciton-templates** task the error disappears. And the error disappears also if I remove the line `pipe(jadeGulp())` 

The other issue is that I don't understand what's the problem. I have no reference which line is influencing it, the part could be solved if the error would thrown synchronous or a file and line number would be provided.

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
SyntaxError: Assigning to rvalue (5:0)
  at Parser.pp.raise (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1745:13)
  at Parser.pp.checkLVal (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1971:12)
  at Parser.pp.parseMaybeUnary (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:999:22)
  at Parser.pp.parseExprOps (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:948:19)
  at Parser.pp.parseMaybeConditional (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:930:19)
  at Parser.pp.parseMaybeAssign (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:908:19)
  at Parser.pp.parseExpression (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:882:19)
  at Parser.pp.parseStatement (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2461:23)
  at Parser.pp.parseTopLevel (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2379:21)
  at Object.parse (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:101:12)
  at reallyParse (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn-globals/index.js:46:20)
  at findGlobals (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/node_modules/acorn-globals/index.js:58:11)
  at addWith (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/node_modules/with/index.js:45:14)
  at parse (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/lib/index.js:149:9)
  at Object.exports.compile (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/jade/lib/index.js:205:16)
  at DestroyableTransform.CompileJade [as _transform] (/Users/awilhelm/website/node_modules/gulp-jade/index.js:34:27)
  at DestroyableTransform.Transform._read (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/awilhelm/website/node_modules/gulp-jade/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:163:7)
  at emitReadable_ (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:67:13)
  at DestroyableTransform.emit (events.js:163:7)
  at emitReadable_ (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /Users/awilhelm/website/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:382:3)
```

**Comment by phated** [comment]
The stack once you start the jade compile is still intact and doesn't include any stream modules, so throwing sync wouldn't get you any more information.  I suggest you reduce the case to just jade and submit an issue to jade.

**Comment by AndyOGo** [comment]
Any solution, i got the same error:

> SyntaxError: Assigning to rvalue (5:0)

**Comment by shinnn** [comment]
@AndyOGo Read @phated's last comment and [this article](http://www.catb.org/esr/faqs/smart-questions.html#forum).

**Comment by AndyOGo** [comment]
Dear wise omniscient @shinnn 
Thank you for giving such a great example of poor ignorant ignorance

**Comment by jamen** [comment]
Hello.  I've seen nothing in that stack trace that point directly back to `gulp-pug`'s or `gulp-jade`'s code.  If you look at it, a lot of the calls point back to the `jade` dependency and specifically the parser (then there is just a lot of extras involving streams).

If I were you, I would try to check [pugjs/pug](https://github.com/pugjs/pug) if there were any issues that were resolved, as that is where the OP was directed, and otherwise open a new issue there.  Also considering just trying to update if you haven't done that already.

On the side note, please try to be friendly.  In open source people are doing you work for free, so all we ask is some respect.  Thank you. :)
